python_binary(
    name = "mysos_test_client",
    source = "mysos_test_client.py",
    entry_point = "mysos.testing.mysos_test_client:proxy_main",
    dependencies = [
        "//src/mysos/common",
        "//3rdparty:sqlalchemy",
        "//3rdparty:twitter.common.app",
        "//3rdparty:twitter.common.log",
        "//3rdparty:twitter.common.dirutil",
    ],
)
