python_library(
  name = 'common',
  sources = [
    '__init__.py',
    'cluster.py',
    'decorators.py',
    'fetcher.py',
    'hdfs.py',
    'pkgutil.py',
    'testing.py',
    'zookeeper.py',
  ],
  dependencies = [
    '//3rdparty:kazoo',
    '//3rdparty:twitter.common.concurrent',
    '//3rdparty:twitter.common.dirutil',
    '//3rdparty:twitter.common.fs',
    '//3rdparty:twitter.common.lang',
    '//3rdparty:twitter.common.log',
    '//3rdparty:twitter.common.quantity',
    '//3rdparty:twitter.common.zookeeper',
  ],
)
